[package]
name = "rustix"
version = "0.1.0"
authors = ["Micah Switzer <micah.switzer.dev@outlook.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"
volatile = "0.2.3"
spin = "0.4.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
